language: php
php:
  - 7.3.0
  - 7.2.13
  - 7.1.25
before_script:
  - if php --ri xdebug >/dev/null; then phpenv config-rm xdebug.ini; fi
  - pecl install ast
  - composer install
script:
  - bin/pahout src
  - vendor/bin/phpunit
  - vendor/bin/phan
