language: php
php:
  - 7.3.0
  - 7.2.13
  - 7.1.25
before_script:
  - phpenv config-rm xdebug.ini
  - pecl install ast
  - composer install
script:
  - bin/pahout src
  - vendor/bin/phpunit
  - vendor/bin/phan
